org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.warning.mode=all

mod_id=probabilitypattern
mod_name=Probability Pattern for AE2
mod_version=0.5.1
mod_group_id=com.tz.statpatterns

java_version=21
minecraft_version=1.21.1
neoforge_version=21.1.169
neoforge_version_range=[21.1.169,)
ae2_version=19.2.17
ae2_version_range=[19,)
ae2wtlib_version=19.2.6

neoForge.parchment.minecraftVersion=1.21
neoForge.parchment.mappingsVersion=2024.07.07

jei_version=19.27.0.336
emi_version=1.1.24+1.21.1
rei_version=16.0.729
guideme_version=21.1.1

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
