#########################################################
# Probability Pattern for AE2 - 1.7.10 port             #
#########################################################
version=0.5.1-1.7.10
group=com.tz.statpatterns
archivesBaseName=probabilitypattern

minecraft_version=1.7.10
forge_version=10.13.4.1448
