/*
 * Probability Pattern for AE2
 * Copyright (C) 2026 TaoLe-si
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.tz.statpatterns.coremod;

import java.util.Map;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.relauncher.FMLRelaunchLog;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin.MCVersion;

/**
 * Coremod bootstrap for Probability Pattern.
 * <p>
 * Registered via the jar manifest (FMLCorePlugin) so the ASM transformer
 * ({@link PPTransformer}) runs before AE2 classes are loaded. Mirrors how
 * Applied Energistics 2 itself ships its transformer coremod.
 */
@MCVersion( "1.7.10" )
public final class PPCore extends DummyModContainer implements IFMLLoadingPlugin
{
	private final ModMetadata metadata = new ModMetadata();

	public PPCore()
	{
		FMLRelaunchLog.info( "[ProbabilityPattern] Core Init" );
		this.metadata.autogenerated = false;
		this.metadata.modId = this.getModId();
		this.metadata.version = this.getVersion();
		this.metadata.name = this.getName();
		this.metadata.description = "Embedded Coremod for Probability Pattern";
	}

	@Override
	public String[] getASMTransformerClass()
	{
		return new String[] { "com.tz.statpatterns.coremod.PPTransformer" };
	}

	@Override
	public String getModContainerClass()
	{
		return "com.tz.statpatterns.coremod.PPCore";
	}

	@Override
	public String getSetupClass()
	{
		return null;
	}

	@Override
	public void injectData( final Map<String, Object> data )
	{
	}

	@Override
	public String getAccessTransformerClass()
	{
		return null;
	}

	@Override
	public ModMetadata getMetadata()
	{
		return this.metadata;
	}

	@Override
	public String getModId()
	{
		return "probabilitypattern-core";
	}

	@Override
	public String getName()
	{
		return "Probability Pattern Core";
	}

	@Override
	public String getVersion()
	{
		return "1.0";
	}

	@Override
	public boolean registerBus( final EventBus bus, final LoadController controller )
	{
		return true;
	}

	@Override
	public String getDisplayVersion()
	{
		return this.getVersion();
	}
}
